name: "test"
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
 build:
  if: github.event_name == 'pull_request' && (github.event.action == 'closed' || github.event.pull_request.merged == true)
  runs-on: ubuntu-latest
  steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'firas'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.FIRAS }}'
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
