name: Release for production

on:
  push:
jobs:
  build:
    name: Generate build

    runs-on: ubuntu-22.04
    steps:
    - name: Set up Elixir
      run: |
        wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
        sudo apt-get update
        sudo apt-get install esl-erlang
        sudo apt-get install elixir
        
